

#ifndef _TOOL_dechat_1_HPP_
#define _TOOL_dechat_1_HPP_

/********************************************************************************/
#include <gatb/gatb_core.hpp>
#include <string.h>
/********************************************************************************/

////////////////////////////////////////////////////////////////////////////////
//
// THIS FILE IS AUTOMATICALLY GENERATED...
//
// THIS IS A SIMPLE EXAMPLE HOW TO USE THE Tool CLASS. IF YOU WANT MORE FEATURES,
// YOU CAN HAVE A LOOK AT THE ToyTool SNIPPET HERE:
//
//      http://gatb-core.gforge.inria.fr/snippets_tools.html
//
////////////////////////////////////////////////////////////////////////////////

class dechat_1 : public Tool
{
public:

	
    // Constructor
    dechat_1 ();

    // Actual job done by the tool is here
    void execute ();
};





/********************************************************************************/
int lordec(int argc, char **argv);
#endif /* _TOOL_dechat_1_HPP_ */

